### ISSUE TITLE
Support required-contact-point-nr=1 ?

### ISSUE THREAD

**Issue by bhudgeons** [akka/akka-management#70] opened 2017-12-08 21:41 UTC
Not sure if this would be useful for anyone else. 

Right now, if you have required-contact-point-nr < 2, we get the good error message "Number of contact points must be greater than 1. For 'single node clusters' simply avoid using the seed bootstraping process, and issue a self-join manually."

Of course, it would be silly in general to use bootstrapping for a single-node cluster, but it would be nice to support the ability to (1) start up a single-cluster node and add add additional nodes later, and (2) support test/stage environments that might run a single-node cluster without having to have special-handling cluster startup logic based on runmode.

**Comment by ktoso** [comment] 2017-12-09 03:30
I’m open to loosening this up.
We’d want to log a warning about “this is a bad idea” though.

Would you want to PR this? (Notice that a big refactor is now pending as a
PR, so best after that one has been merged)

-- 
Cheers,
Konrad 'ktoso <http://kto.so>' Malawski
Akka <http://akka.io/> @ Lightbend <http://lightbend.com/>

On December 9, 2017 at 6:41:46, Brandon Hudgeons (notifications@github.com)
wrote:

Not sure if this would be useful for anyone else.

Right now, if you have required-contact-point-nr < 2, we get the good error
message "Number of contact points must be greater than 1. For 'single node
clusters' simply avoid using the seed bootstraping process, and issue a
self-join manually."

Of course, it would be silly in general to use bootstrapping for a
single-node cluster, but it would be nice to support the ability to (1)
start up a single-cluster node and add add additional nodes later, and (2)
support test/stage environments that might run a single-node cluster
without having to have special-handling cluster startup logic based on
runmode.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-management/issues/70>, or mute the thread

**Comment by bhudgeons** [comment] 2017-12-11 21:35
Sure ... will wait for PR.

**Comment by ktoso** [comment] 2017-12-20 11:39
Done in 0.7.1 :)

**Comment by ktoso** [comment] 2017-12-20 11:39
In 0.7.0 even, but use the 1 revision

**Closed by ktoso** 2017-12-20 11:39 UTC

**Comment by Svince123** [comment] 2019-08-01 23:53
Hi, can we start one node but configure 3 ?

**Comment by handsomehari** [comment] 2020-05-02 07:21
Add 

> @ktoso Hi, can we start one node but configure 3 endpoints and then start the other two nodes later ?
> 
> I am not able to start only one node (127.0.0.1) with the following configuration:
> 
> Configuration
> 
> ```
> akka {
>   loglevel = INFO
> 
>   actor {
>     provider = "cluster"
>   }
> 
>   remote {
>     artery {
>       enabled = on
>       transport = tcp
>       canonical.port = 2551
>     }
>   }
> 
> 
> }
> 
> #coorindated-shutdown
> akka.cluster.shutdown-after-unsuccessful-join-seed-nodes = 30s
> akka.coordinated-shutdown.exit-jvm = on
> #coorindated-shutdown
> 
> #discovery
> akka.discovery {
>   config.services = {
>     local-cluster = {
>       endpoints = [
>         {
>           host = "127.0.0.1"
>           port = 8558
>         },
>         {
>           host = "127.0.0.2"
>           port = 8558
>         },
>         {
>           host = "127.0.0.3"
>           port = 8558
>         }
>       ]
>     }
>   }
> }
> #discovery
> 
> #health
> akka.management.health-checks {
>   readiness-path = "health/ready"
>   liveness-path = "health/alive"
> }
> #health
> 
> akka.management.http {
>   route-providers-read-only = false
> }
> # registers bootstrap routes to be included in akka-management's http endpoint
> http.routes {
>   cluster-bootstrap = "akka.management.cluster.bootstrap.ClusterBootstrap$"
> }
> 
> #bootstrap
> akka.management {
>   cluster.bootstrap {
>     new-cluster-enabled = on
>     contact-point-discovery {
>       required-contact-point-nr = 1
>       service-name = "local-cluster"
>       service-namespace = "<service-namespace>"
>       port-name = ""
>       protocol = "tcp"
>       effective-name = "<effective-name>"
>       discovery-method = config
>       # Timeout for getting a reply from the service-discovery subsystem
>       resolve-timeout = 3 seconds
>       # This timeout represents a tradeoff between safety and quickness of forming a new cluster.
>       stable-margin = 5 seconds
>       # Interval at which service discovery will be polled in search for new contact-points
>       #
>       # Note that actual timing of lookups will be the following:
>       # - perform initial lookup; interval is this base interval
>       # - await response within resolve-timeout
>       #   (this can be larger than interval, which means interval effectively is resolveTimeout + interval,
>       #    this has been specifically made so, to not hit discovery services with requests while the lookup is being serviced)
>       #   - if failure happens apply backoff to interval (the backoff growth is exponential)
>       # - if no failure happened, and we receive a resolved list of services, schedule another lookup in interval time
>       #   - if previously failures happened during discovery, a successful lookup resets the interval to `interval` again
>       # = repeat until stable-margin is reached
>       interval = 1 second
> 
>       # Adds "noise" to vary the intervals between retries slightly (0.2 means 20% of base value).
>       # This is important in order to avoid the various nodes performing lookups in the same interval,
>       # potentially causing a thundering heard effect. Usually there is no need to tweak this parameter.
>       exponential-backoff-random-factor = 0.2
> 
>       # Maximum interval to which the exponential backoff is allowed to grow
>       exponential-backoff-max = 15 seconds
>     }
>   }
> }
> #bootstrap
> ```
> 
> Code => available in akka-management
> 
> ```
> package akka.cluster.bootstrap
> 
> import akka.actor.ActorSystem
> import akka.cluster.Cluster
> import akka.management.cluster.bootstrap.ClusterBootstrap
> import akka.management.scaladsl.AkkaManagement
> import com.typesafe.config.{ Config, ConfigFactory }
> 
> //#main
> object Node1 extends App {
>   new Main(1)
> }
> 
> object Node2 extends App {
>   new Main(2)
> }
> 
> object Node3 extends App {
>   new Main(3)
> }
> 
> class Main(nr: Int) {
> 
>   val config: Config = ConfigFactory.parseString(s"""
>       akka.remote.artery.canonical.hostname = "127.0.0.$nr"
>       akka.management.http.hostname = "127.0.0.$nr"
>     """).withFallback(ConfigFactory.load())
>   val system = ActorSystem("local-cluster", config)
> 
>   AkkaManagement(system).start()
> 
>   ClusterBootstrap(system).start()
> 
>   Cluster(system).registerOnMemberUp({
>     system.log.info("Cluster is up!")
>   })
> }
> //#main
> ```
> 
> Log
> 
> ```
> [INFO] [08/02/2019 20:46:02.727] [local-cluster-akka.actor.default-dispatcher-10] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator] Contact point [akka://local-cluster@127.0.0.1:2551] returned [0] seed-nodes []
> [INFO] [08/02/2019 20:46:03.421] [local-cluster-akka.actor.default-dispatcher-2] [LowestAddressJoinDecider(akka://local-cluster)] Exceeded stable margins but missing seed node information from some contact points [ResolvedTarget(127.0.0.3,Some(8558),None), ResolvedTarget(127.0.0.2,Some(8558),None)] (out of [ResolvedTarget(127.0.0.1,Some(8558),None), ResolvedTarget(127.0.0.3,Some(8558),None), ResolvedTarget(127.0.0.2,Some(8558),None)])
> [WARN] [08/02/2019 20:46:03.479] [local-cluster-akka.actor.default-dispatcher-4] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator/contactPointProbe-127.0.0.2-8558] Probing [http://127.0.0.2:8558/bootstrap/seed-nodes] failed due to: Probing timeout of [http://127.0.0.2:8558]
> [WARN] [08/02/2019 20:46:03.479] [local-cluster-akka.actor.default-dispatcher-3] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator/contactPointProbe-127.0.0.3-8558] Probing [http://127.0.0.3:8558/bootstrap/seed-nodes] failed due to: Probing timeout of [http://127.0.0.3:8558]
> [ERROR] [08/02/2019 20:46:03.479] [local-cluster-akka.actor.default-dispatcher-4] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator/contactPointProbe-127.0.0.2-8558] Overdue of probing-failure-timeout, stop probing, signaling that it's failed
> [ERROR] [08/02/2019 20:46:03.479] [local-cluster-akka.actor.default-dispatcher-3] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator/contactPointProbe-127.0.0.3-8558] Overdue of probing-failure-timeout, stop probing, signaling that it's failed
> [INFO] [08/02/2019 20:46:03.479] [local-cluster-akka.actor.default-dispatcher-14] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator] Received signal that probing has failed, scheduling contact point probing again
> [INFO] [08/02/2019 20:46:03.479] [local-cluster-akka.actor.default-dispatcher-14] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator] Received signal that probing has failed, scheduling contact point probing again
> [INFO] [08/02/2019 20:46:03.843] [local-cluster-akka.actor.default-dispatcher-11] [HttpClusterBootstrapRoutes(akka://local-cluster)] Bootstrap request from 127.0.0.1:58125: Contact Point returning 0 seed-nodes ([TreeSet()])
> [INFO] [08/02/2019 20:46:03.845] [local-cluster-akka.actor.default-dispatcher-3] [akka://local-cluster@127.0.0.1:2551/system/bootstrapCoordinator] Contact point [akka://local-cluster@127.0.0.1:2551] returned [0] seed-nodes []
> ```



Create a new class in your project which should extend "akka.management.cluster.bootstrap.LowestAddressJoinDecider" and override method isConfirmedCommunicationWithAllContactPointsRequired and always return false.

Configure your decider class under join-decider property in your conf file

@Override
public boolean isConfirmedCommunicationWithAllContactPointsRequired(SeedNodesInformation info) {
	return false;
}

join-decider {
      class = "com.test.MyLowestAddressJoinDecider"
}

With this change, the cluster would be formed with single contact point.
