### ISSUE TITLE
Test bootstrap on OpenShift

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#365] opened 2018-10-31 09:23 UTC
- [x] Manual test and update documentation
- [x] Minishift in travis?
    - I don't think this is worth it if we're going to test against a real open shift cluster. More users have access to minikube than minishift
- [x] External OpenShift cluster as part of CI?

**Comment by TimMoore** [comment] 2018-11-08 00:47
Looks like a duplicate of #175 (but maybe close that one and keep this one?)

This should also include an example in https://github.com/akka/akka-management/tree/master/bootstrap-demo (and documented at https://developer.lightbend.com/docs/akka-management/current/bootstrap/recipes.html)

**Comment by chbatey** [comment] 2018-11-13 17:50
Both the k8s demos have instructions for open shift and we have a separate test suite for a real open shift

**Closed** 2018-11-16 16:39 UTC
Labels: 0 - new, t:bootstrap

**Comment by dwijnand** [comment] 2018-11-27 12:21
Where are the outcomes of this?

* the updated docs
* did you end up setting up Minishift in Travis? not sure what the checkmark is meant to indicate
* are there docs for how to setup CI testing with an external OpenShift cluster?

**Comment by chbatey** [comment] 2018-11-27 12:35
We stuck with vanilla minikube for travis. Our testing against open shift
is a real cluster used from the CI of this project:
https://github.com/akka/akka-kubernetes-tests
For how that works check out its travis file. I don’t think anything CI
related belongs in Akka Amanagement docs or do you mean something you can
use for another project?

**Comment by dwijnand** [comment] 2018-11-27 12:40
I was looking for the updated bootstrap on OpenShift docs, but maybe we ended up going non-Openshift specific?

I saw that updates were made to https://developer.lightbend.com/docs/akka-management/current/bootstrap/index.html so I'll start there, but let me know if there's more info in other places (I'll check out akka-kubernetes-tests's travis file).

**Comment by chbatey** [comment] 2018-11-27 12:48
Also for kubernetes specifics:
https://developer.lightbend.com/docs/akka-management/current/bootstrap/recipes.html

Only changes needed for the demos were to put them in a namespace
