### ISSUE TITLE
akka.discovery.ServiceDiscovery$DiscoveryTimeoutException: Dns resolve did not respond within 5.000 s

### ISSUE THREAD

**Issue by shanmukha511** [akka/akka-management#660] opened 2020-04-20 10:25 UTC
Hi team,

Did anyone faced below error?
"akka.discovery.ServiceDiscovery$DiscoveryTimeoutException: Dns resolve did not respond within 5.000 s"
How to resolve this?

**Comment by raboof** [comment] 2020-04-20 13:09
You might have more luck at https://discuss.akka.io rather than on the issue tracker.

This sounds like DNS problems on your system. What kind of OS is this on? Is it running in a container or on 'bare metal'?

**Comment by shanmukha511** [comment] 2020-04-20 14:30
Hi @raboof,

We are running on k8 like pods just want to know whether its kubernetes dns issue or akka issue and even i dont see any logs for kube-dns?

**Comment by shanmukha511** [comment] 2020-04-21 10:20
pods which are throwing error os is alpine

**Comment by raboof** [comment] 2020-04-21 10:30
duplicate of https://github.com/akka/akka/issues/28948, please don't cross-post :/

**Closed by raboof** 2020-04-21 10:30 UTC
