### ISSUE TITLE
Version is broken in the docs

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#265] opened 2018-08-14 07:52 UTC
At https://developer.lightbend.com/docs/akka-management/current/

The version shows as `0.17.0+20180718-1128` as techhub when publishing the docs modifies build.sbt

We need to change techhub or stop using git versioning or stop using a build.sbt to make it work.

**Comment by patriknw** [comment] 2018-08-14 07:57
It's working in Alpakka somehow. Don't know if it's related but Alpakka is using `addSbtPlugin("com.dwijnand" % "sbt-dynver" % "3.0.0+4-1be64920")`

**Comment by patriknw** [comment] 2018-08-14 07:58
and I'm pretty sure it has been working here also, previously

**Comment by patriknw** [comment] 2018-08-15 16:17
Duplicate of https://github.com/akka/akka-management/issues/255

**Closed by patriknw** 2018-08-15 16:17 UTC
