### ISSUE TITLE
KubernetesApiIntegrationTest: Kubernetes lease resource should be able to be created

### ISSUE THREAD

**Issue by raboof** [akka/akka-management#724] opened 2020-07-24 14:35 UTC
https://travis-ci.org/github/akka/akka-management/jobs/710781311

```
[info] KubernetesApiIntegrationTest:
[info] Kubernetes lease resource
[info] - should be able to be created *** FAILED ***
[info]   The future returned an exception of type: akka.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiIntegrationTest.scala:56)
[info] - should be able to read back with same version *** FAILED ***
[info]   "[522]" did not equal "[]" (KubernetesApiIntegrationTest.scala:66)
[info]   Analysis:
[info]   "[522]" -> "[]"
```

**Comment by jrudolph** [comment] 2020-08-11 12:10
Duplicate of #695?

**Closed by jrudolph** 2020-08-11 12:10 UTC
Labels: failed, t:kubernetes
