### ISSUE TITLE
akka cluster fail to connect in IPV6 environment.

### ISSUE THREAD

**Issue by WayneWang12** [akka/akka-management#847] opened 2021-02-08 06:41 UTC
Comunication failed. Seems that it is due to the way ipv6 address used in uri. I have to rewrite the join decider to make it run:
```scala
class IPV6JoinDecider(system: ActorSystem, settings: ClusterBootstrapSettings)
  extends LowestAddressJoinDecider(system, settings) {

  override protected def hostMatches(oh: String, target: ServiceDiscovery.ResolvedTarget): Boolean = {
    val host = oh.stripPrefix("[").stripSuffix("]")
    host == target.host || target.address.map(_.getHostAddress).contains(host)
  }
}
```

Why is that? because akka bind failed when i am using simple ipv6 address without brackets. I have to change akka hostname to `[fdbd:dc03:ff:1:1:123:123:123]` then it can find the right nodes.

Wish this can be fix

**Comment by johanandren** [comment] 2021-02-08 07:06
I thought this was working fine (test coverage in [akka.management.cluster.bootstrap.SelfAwareJoinDeciderIPv6Spec](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala#L244)) but maybe I don't understand what is the exact issue, could you elaborate a bit or share a minimal reproducer project?

**Comment by WayneWang12** [comment] 2021-02-08 07:40
> I thought this was working fine (test coverage in [akka.management.cluster.bootstrap.SelfAwareJoinDeciderIPv6Spec](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala#L244)) but maybe I don't understand what is the exact issue, could you elaborate a bit or share a minimal reproducer project?

I see this code in the test you refered:
```     ClusterBootstrap(system).setSelfContactPoint(s"http://[240b:c0e0:202:5e2b:b424:2:0:450]:$managementPort/test")
```

Problem is that how can I tell akka management to use host like `[240b:c0e0:202:5e2b:b424:2:0:450]`. Usually IP comes from environment variable. It's certainly without brackets. The common way I config the hostname:
```
akka.management.http.hostname = ${?IPV4}
akka.management.http.hostname = ${?IPV6}
```
Without more concerete knowlege, the latter one will fail because it has no brackets. And if I'm using consul or other service locator, the discovered IPv6 is also without brackets. Then if I set `akka.management.http.hostname = [${?IPV6}]`, It has to strip the brackets to make two equal.

**Comment by WayneWang12** [comment] 2021-02-08 08:09
I look into this [test](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala) carefully. And I found the test case may need to be changed. Because here you assumed all the IPV6s are with brackets. But in real environment, it comes naturally without it. It lacks integretion tests. Seems that if you change the test's configuration to this:

```scala
  val disabled =
    ConfigFactory.parseString(""" 
    akka.management.cluster.bootstrap.new-cluster-enabled=off
    akka.management.http.hostname = "240b:c0e0:202:5e2b:b424:2:0:450"
    """)
```
Then it will fail.

**Comment by johanandren** [comment] 2021-02-08 09:23
I see, thanks for the clarification. If you would like to PR an improvement that'd be welcome.

**Comment by WayneWang12** [comment] 2021-02-09 05:57
> I see, thanks for the clarification. If you would like to PR an improvement that'd be welcome.

Sure. I'll make a pull request in spring festival holiday.

**Comment by WayneWang12** [comment] 2021-04-15 14:22
> I see, thanks for the clarification. If you would like to PR an improvement that'd be welcome.

Hi Johan, I've made two pull request for ipv6 support(akka/akka#30190, #888 ). Would you like please review it?

**Comment by raboof** [comment] 2021-06-02 12:51
Let's close this here since #888 is merged, though likely this doesn't yet work end-to-end until we also merge akka/akka#30190, hopefully soon). Feel free to reopen (or open a new issue) when it turns out there is something missing still.

**Closed by raboof** 2021-06-02 12:51 UTC
Labels: 1 - triaged, t:bootstrap
